export const env = {
    HARD_FUEL_GAP_KM: Number(process.env.HARD_FUEL_GAP_KM) || 350,

    FUEL_STATION_SEARCH_RADIUS: Number(process.env.FUEL_STATION_SEARCH_RADIUS) || 30000,
    NEARBY_STOPS_SEARCH_RADIUS: Number(process.env.NEARBY_STOPS_SEARCH_RADIUS) || 25000,
    FUEL_ALONG_ROUTE_RADIUS: Number(process.env.FUEL_ALONG_ROUTE_RADIUS) || 8000,
    PLACES_SEARCH_RADIUS: Number(process.env.PLACES_SEARCH_RADIUS) || 50000,
    FUEL_STATIONS_RADIUS: Number(process.env.FUEL_STATIONS_RADIUS) || 5000,
    PLANNER_NEARBY_RADIUS: Number(process.env.PLANNER_NEARBY_RADIUS) || 35000,

    PACE_LEISURELY_KM_PER_DAY: Number(process.env.PACE_LEISURELY_KM_PER_DAY) || 150,
    PACE_LEISURELY_HOURS_PER_LEG: Number(process.env.PACE_LEISURELY_HOURS_PER_LEG) || 2,
    PACE_LEISURELY_MIN_SPACING: Number(process.env.PACE_LEISURELY_MIN_SPACING) || 80,
    PACE_LEISURELY_MAX_SPACING: Number(process.env.PACE_LEISURELY_MAX_SPACING) || 200,

    PACE_MODERATE_KM_PER_DAY: Number(process.env.PACE_MODERATE_KM_PER_DAY) || 200,
    PACE_MODERATE_HOURS_PER_LEG: Number(process.env.PACE_MODERATE_HOURS_PER_LEG) || 2.5,
    PACE_MODERATE_MIN_SPACING: Number(process.env.PACE_MODERATE_MIN_SPACING) || 120,
    PACE_MODERATE_MAX_SPACING: Number(process.env.PACE_MODERATE_MAX_SPACING) || 280,

    PACE_FAST_KM_PER_DAY: Number(process.env.PACE_FAST_KM_PER_DAY) || 300,
    PACE_FAST_HOURS_PER_LEG: Number(process.env.PACE_FAST_HOURS_PER_LEG) || 3.5,
    PACE_FAST_MIN_SPACING: Number(process.env.PACE_FAST_MIN_SPACING) || 180,
    PACE_FAST_MAX_SPACING: Number(process.env.PACE_FAST_MAX_SPACING) || 400,

    AVOID_LONG_DAYS_KM: Number(process.env.AVOID_LONG_DAYS_KM) || 280,
    DEFAULT_MAX_KM_PER_DAY: Number(process.env.DEFAULT_MAX_KM_PER_DAY) || 400,

    PROBE_SEARCH_RADIUS: Number(process.env.PROBE_SEARCH_RADIUS) || 30000,
    PROBE_DISTANCE_THRESHOLD: Number(process.env.PROBE_DISTANCE_THRESHOLD) || 2000,
    PROBE_DISTANCE_LONG_TRIP: Number(process.env.PROBE_DISTANCE_LONG_TRIP) || 300,
    PROBE_MAX_RESULTS_LONG_TRIP: Number(process.env.PROBE_MAX_RESULTS_LONG_TRIP) || 20,
    PROBE_MAX_RESULTS_SHORT_TRIP: Number(process.env.PROBE_MAX_RESULTS_SHORT_TRIP) || 10,

    LEG_TARGET_MIN_KM: Number(process.env.LEG_TARGET_MIN_KM) || 100,
    LEG_MIN_KM: Number(process.env.LEG_MIN_KM) || 140,
    LEG_MAX_KM: Number(process.env.LEG_MAX_KM) || 220,
    LEG_SPACING_KM: Number(process.env.LEG_SPACING_KM) || 50,
    LEG_AVOID_LONG_DAYS_ADD_KM: Number(process.env.LEG_AVOID_LONG_DAYS_ADD_KM) || 60,

    NEXT_PUBLIC_PLANNER_NEARBY_RADIUS: Number(process.env.NEXT_PUBLIC_PLANNER_NEARBY_RADIUS) || 35000,
};